apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _csi-rclone-namespace.yaml
- csi-controller-rbac.yaml
- csi-controller-rclone.yaml
- csi-nodeplugin-rbac.yaml
- csi-nodeplugin-rclone.yaml
- csi-rclone-storageclass.yaml

